### PR TITLE
Add an html example for basic usage

### PR DESCRIPTION
**Pull request by damascene**
Created an html example for basic usage

### CODE REVIEW

**Comment by damascene** [comment]
Here is it in the working

https://github.com/user-attachments/assets/4825b896-69e7-4a7f-bdeb-1cb17ecb8c79

**Comment by nostrband** [comment]
This looks great! But how about we put the example into a separate file? I.e. /examples/usage.html ? It's big enough to have it's own file, and we might also create more examples with more advanced usage, i.e. as part of a react app, etc.

**Comment by damascene** [comment]
@nostrband Thank you. Please check the new additions. I've tried to address your concerns.

**Comment by nostrband** [comment]
Thanks, @damascene !

**Pull request merged**
